version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=covid-db
      - DB_PORT=27017
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./dbdata:/data/db
